Feature/easy admin
Margauxfeslard/book-offensive pull request #15
Opened 2022-05-11 14:16 UTC by manolis59

Découverte de git pr work in progress

2022-05-14 20:47 UTC, dunglas requested changes

2022-05-14 20:47 UTC, dunglas commented on src/Controller/Admin/BookCrudController.php
> +    /*
You can delete this code as it is unused.

2022-05-14 20:47 UTC, dunglas commented on src/Controller/Admin/BorrowCrudController.php
> +    /*
Same here.

2022-05-14 20:47 UTC, dunglas commented on src/Controller/Admin/DashboardController.php
> +        // Option 1. You can make your dashboard redirect to some common page of your backend
Same here, remove the useless auto-generated code everywhere.

2022-05-14 20:47 UTC, dunglas commented on src/Controller/Admin/DashboardController.php
> +        // yield MenuItem::linkToCrud('The Label', 'fas fa-list', EntityClass::class);
To delete

2022-05-14 20:47 UTC, dunglas commented on src/Controller/Admin/PhysicalBookCrudController.php
> +    /*
To delete

2022-05-14 20:47 UTC, dunglas commented on src/Controller/Admin/ReviewCrudController.php
> +    /*
To delete

2022-05-16 09:18 UTC, Margauxfeslard requested changes
Can you delete this file please : templates/test2.html.twig ?

2022-05-16 09:26 UTC, Margauxfeslard approved these changes

2022-05-16 09:31 UTC, dunglas approved these changes

2022-05-16 09:31 UTC, dunglas commented on src/Controller/Admin/UserCrudController.php
> +
```suggestion
```
Blank line to remove (use PHP CS Fixer)

2022-05-16 09:31 UTC, dunglas commented on src/Controller/Admin/DashboardController.php
> +
```suggestion   
```

Blank line to remove (use PHP CS Fixer)

2022-05-16 13:08 UTC, merged